name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: Unit tests Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.20"
            otp: "29"
          - elixir: "1.19"
            otp: "28"
          - elixir: "1.18"
            otp: "27"
          - elixir: "1.17"
            otp: "27"
          - elixir: "1.16"
            otp: "26"
          - elixir: "1.15"
            otp: "26"
          - elixir: "1.14"
            otp: "25"
          - elixir: "1.13"
            otp: "25"
          - elixir: "1.12"
            otp: "24"

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore deps cache
        uses: actions/cache@v6
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Restore _build cache
        uses: actions/cache@v6
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Restore plt cache
        if: ${{ matrix.otp == '29' && matrix.elixir == '1.20' }}
        uses: actions/cache@v6
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-plt-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Install deps
        run: mix deps.get

      - name: Check Formatting
        if: ${{ matrix.otp == '29' && matrix.elixir == '1.20' }}
        run: mix format --check-formatted

      - name: Run unit tests
        run: |
          mix clean
          mix test

      - name: Run unit tests with persistent_term backend
        run: |
          mix clean
          mix test
        env:
          SCHEMA_PROVIDER: persistent_term

      - name: Run dialyzer
        if: ${{ matrix.otp == '29' && matrix.elixir == '1.20' }}
        run: |
          mkdir -p priv/plts/{local,core}
          MIX_ENV=test mix dialyzer

  federation_compatibility_tests:
    name: Federation compatibility tests
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - elixir: "1.20"
            otp: "29"

    steps:
      - name: Save action secrets
        id: actionsecrets
        shell: bash
        run: |
          if [ $IS_FORK != "true" ]; then
            echo "github_token=$GITHUB_TOKEN" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_FORK: ${{ github.event.pull_request.head.repo.full_name != github.repository }}

      - name: Checkout
        uses: actions/checkout@v7

      - name: Extract federation compatibility schema
        run: |
          docker buildx build \
            --target schema-export \
            --output type=local,dest=./federation_compatibility \
            -f federation_compatibility_dockerfile \
            .

      - name: Test subgraph compatibility
        uses: apollographql/federation-subgraph-compatibility@v3
        with:
          compose: "federation_compatibility_docker_compose.yml"
          schema: "federation_compatibility/schema.graphql"
          token: ${{ steps.actionsecrets.outputs.github_token }}
          port: 4001
          failOnWarning: false
          failOnRequired: true
          debug: true
